---

- name: "Converge"
  hosts: all
  become: true
  gather_facts: true
  vars:
    state: present
    iac_blueprint:
      kubernetes:
        container_runtime: "crio"
  roles:
    - role: ansible-iac-role-kubernetes
