---

- name: "Verify CRI-O component absence"
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "Checking component absence"
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /root/.kube/config
        - /etc/kubernetes/kubelet.conf
        - /etc/cni/net.d/10-flannel.conflist
      register: component_files

    - name: "Checking component absence facts"
      ansible.builtin.assert:
        that:
          - "(component_files.results | selectattr('stat.exists') | list | length) == 0"
        fail_msg: "CRI-O Kubernetes component absence verification failed"
