---

- name: "Converge"
  hosts: all
  become: true
  gather_facts: true
  vars:
    state: present
    iac_blueprint:
      kubernetes:
        control_plane_state: "present"
        cni_state: "present"
  roles:
    - role: ansible-iac-role-kubernetes
