---

- name: "Install Kubernetes before uninstall verification"
  hosts: all
  become: true
  gather_facts: true
  vars:
    state: present
    iac_blueprint:
      kubernetes:
        control_plane_state: "present"
        cni_state: "present"
  roles:
    - role: ansible-iac-role-kubernetes

- name: "Uninstall Kubernetes"
  hosts: all
  become: true
  gather_facts: true
  vars:
    state: uninstall
    iac_blueprint:
      kubernetes: {}
  roles:
    - role: ansible-iac-role-kubernetes
